### ISSUE TITLE
Algorithms and datastructures road map

### ISSUE THREAD

**Issue by er888kh** [TheAlgorithms/Rust#344]
Since #3 is already overcrowded and we need to have our roadmap somewhere visible, I figured I should open a new issue. The list is currently my own to-do list, and maintainers' suggestions, additions, and ideas in general will be incorporated here. Also suggestions from community are welcome.

## Maths
- [x] Big number support (#371)
- [ ] Chinese remainder theorem (WIP @Logicless-Coder)
- [ ] Elliptic curve operations

## Graph
- [x] 2-SAT (#345 )
- [x] Eulerian path
- [x] All pairs shortest path (#366)
- [ ] Bipartite matching
- [ ] A*

## Strings
- [x] Suffix array
- [ ] Suffix tree

## Cryptography
- [x] A generic implementation for HMAC (#351)
- [x] Salsa20 and Chacha20 (#363)
- [x] Poly1305 message authentication code (#371)

**Comment by YurySolovyov** [comment]
[Hash Array Mapped Trie (HAMT)](https://en.wikipedia.org/wiki/Hash_array_mapped_trie) ?

**Comment by er888kh** [comment]
> [Hash Array Mapped Trie (HAMT)](https://en.wikipedia.org/wiki/Hash_array_mapped_trie) ?

Seems like a cool datastructure!

**Comment by YurySolovyov** [comment]
> > [Hash Array Mapped Trie (HAMT)](https://en.wikipedia.org/wiki/Hash_array_mapped_trie) ?
> 
> Seems like a cool datastructure!
> 
> Should I add it as WIP by you @YurySolovyov ?

No, I'm still relatively new to rust, so I don't want to claim this item, it was purely a suggestion. HAMT combines hashing, trees and some binops, so I was hoping to learn how it can be done, that's all.

**Comment by er888kh** [comment]
> No, I'm still relatively new to rust, so I don't want to claim this item, it was purely a suggestion. HAMT combines hashing, trees and some binops, so I was hoping to learn how it can be done, that's all.

Maybe you can start by implementing the hash function for HAMT first, because datastructures are known to be a bit tricky to implement in rust, and this certainly isn't a trivial one.

In any case, you are more than welcome to contribute. Some other options you have are:
1- ChaCha20. Just open RFC8439 and start writing code. This can be implemented in ~30 LoC.
2- All Pairs Shortest Path.
3- Bipartite matching. Use Dinic which is already implemented.

**Comment by er888kh** [comment]
@siriak
Can we use a third party library for bignum support? I really want to implement some cool stuff with elliptic curves (e.g. Lenstra ECM, Diffie-Hellman, MQV method, etc.), but creating bignum support from scratch is a big undertaking and a bit futile (either the code won't be readable/educational, or would be prohibitively slow). Maybe we can hide the code that depend on 3-rd party library behind a feature flag, such that "normal" builds don't pull the dependency?

**Comment by siriak** [comment]
@er888kh  Are you talking about `BigInteger` and `BigDecimal` from `java.math`? Sure

**Comment by er888kh** [comment]
> @er888kh Are you talking about `BigInteger` and `BigDecimal` from `java.math`? Sure

Yes. I'm not sure if using one of the gmp interfaces makes sense (I don't have windows, I'm not sure whether windows users can easily compile gmp C library or whether it can be retrieved automatically), but in case that's possible, it would be the best solution.

The other solution is to use one of the native rust based implementations. But that would come with a hefty performance penalty (nothing beats literally decades of hand optimized assembly code).

**Comment by siriak** [comment]
Ooops, wrong repo :) I thought it was in the Java repo :) I don't have a Windows pc either, so can't comment about gmp. It's up to your discretion as I don't have an opinion on that matter

**Comment by er888kh** [comment]
@siriak 
I implemented poly1305 using `num-bigint` library. If you accept that implementation and library, we can move on to other stuff. For example elliptic curve code shouldn't be that hard once I implement some primitive operations/algorithms.

**Comment by EwoutH** [comment]
Could I request the A* (a.k.a. A-star) graph search algorithm [wiki](https://en.wikipedia.org/wiki/A*_search_algorithm)?

See the [original paper](https://doi.org/10.1109%2FTSSC.1968.300136) and the [NetworkX implementation](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.shortest_paths.astar.astar_path.html).

**Comment by Arjun31415** [comment]
Could you please look at my PR #377 for Bipartite Matching. If found suitable, I can add Hopcroft Karp in a similar fashion

**Comment by GentBinaku** [comment]
Hi, if anybody could review my PR https://github.com/TheAlgorithms/Rust/pull/378

**Comment by Logicless-Coder** [comment]
Hi, if open I would like to pick up "Chinese Remainder Theorem" under the "Math" category.

**Comment by GentBinaku** [comment]
@Logicless-Coder https://github.com/TheAlgorithms/Rust/pull/413 if you think you can improve it please go ahead and make a commit

**Comment by Logicless-Coder** [comment]
@GentBinaku are there any known issues/bugs/improvements?

**Comment by GentBinaku** [comment]
@Logicless-Coder  The test pass and the checks pass, so you might dig more into it if you want too

**Comment by Logicless-Coder** [comment]
@GentBinaku The test cases were weak, I found a test which fails and found the problem being in the modinverse function. It requires usage of extended Euclidean algorithm and not just the regular Euclidean algorithm of calculating GCD. I am writing the extended algorithm next to verify this claim.

**Comment by GentBinaku** [comment]
@GentBinaku  Please do I would like to see the code

**Comment by Lets-coD** [comment]
Hi admin, 
i would like to work on Eulerian path

**Comment by mohit07raghav19** [comment]
Hi , **Suffix array** can be implemented using external crate _"suffix"_ with lesser lines of code ensuring optimistic code.
So, should i add it to this ? OR implement it using **Manber-Myers algorithm** which doesn't uses external crate but it can become more complex ?

**Comment by siriak** [comment]
What do you mean by using `suffix` crate? Just using their implementation of suffix array? I'd say using Manber-Myers algorithm is preferable because we must see implementation details
